### ISSUE TITLE
Kanban: Rent-A-Ride

### ISSUE THREAD

**Issue by Piercel2022** [EddyShimwa/Rent-A-Ride#17]
Hello Reviewer

For this final capstone project, we are 3 people in a team

@kennedyowusu 
@EddyShimwa 
@Piercel2022 

https://github.com/users/EddyShimwa/projects/3

![kanban](https://github.com/EddyShimwa/Rent-A-Ride/assets/98626003/4d0cafc1-8ec4-4a72-8a81-db4391cf9178)

**Comment by mcrd25** [comment]
Hi Team, 

Great work on making the changes 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.



## Highlights
- You've basically met all requirements with one exception. 👍 

## Optional suggestions
- Your link is a link the Rent-A-Ride-app repository as opposed to project. Did you mean to add the project link? If not please do add that as well, if not add correct the link.
- [OPTIONAL] Ensure that you are adding realistic weight to your tasks.
- [OPTIONAL] Consider adding labels to your issues, it makes it easier to filter by different types and gives another added level of differentiation among tasks (front-end vs back-end etc.)

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear.

**_Please, do not open a new Issue for re-reviews. You should use the same Issue submitted for the first review, either valid or invalid unless it is requested otherwise._**



------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by mcrd25** [comment]
Hi Team, 

In my opinion, you are ready to move on to the next step! ⏭️  
Good luck! 🎉 



Feel free to leave any questions or comments in the Issue thread if something is not 100% clear.


Cheers and Happy coding!👏👏👏


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
